### PR TITLE
Audio

### LINKED ISSUE #9: Audio Rendering
Play audio:
 - [x] Play a single sfx
 - [x] Play multiple sfx
 - [x] ~~Attach any kind of mixer effect (if that's possible in Bevy). i.e. this mostly comes to down to investigating the capabilities of Bevy and linking some useful stuff here.~~ Not possible with Bevy's default audio plugin, which basically can just decode MP3 and play SFX to whatever default audio output device. https://github.com/RustAudio/dsp-chain may be what we want

### PR DESCRIPTION
**Pull request by ocornoc**
Adds a basic sound effect and makes `main.rs` play *every* loaded sound effect every time the LMB is clicked.

Closes #9

### CODE REVIEW

**Review by martindevans — APPROVED** [review]
The basic audio playback looks ok, but try not to include so many cosmetic changes in future PRs.

**Comment by ocornoc** [comment]
Until we get Bots set up, which has a feature to force `cargo fmt`, I'm just calling it for every PR

**Review by Nyefari — APPROVED** [review]
I'm not a huge fan of this implementation (play everything at once), but if it works for MVP1 tier for everyone else it works for me. For MVP2 I would like to see something that can be triggered by other systems using events, personally.

**Comment by ocornoc** [comment]
This was the quickest way I could implement it, just to show specifically audio playing etc. I've already added custom events and event handling with the camera PR, so copying those principles should be straightforward

**Review by Jerald — APPROVED** [review]

**Pull request merged**
